import { ToyModel } from '../app/toy-browse/state/toy-browse-model';

export const toys: ToyModel[] = [
  {
    toyOwner: 'farhad', //identification
    toyName: 'Car set',
    ageType: 'kid',
    toyCountry: 'BGD',
    toyCreated: new Date('2024-03-16'),
    toyPrice: 100,
    currency: 'DKK',
    detailsOfToy: 'boiled rice',
    imageUrl: 'assets/images/toys/cars.jpeg',
    isLike: true,
    isLove: true,
    reaction: {
      numberLikes: 1,
      numberLoves: 3,
      numberDislikes: 0,
    },
    ratings: 9,
    active: true,
  },
  {
    toyOwner: 'ayan',
    toyName: 'Plane',
    ageType: 'boy',
    toyCountry: 'THA',
    toyCreated: new Date('2023-05-25'),
    toyPrice: 100,
    currency: 'DKK',
    detailsOfToy:
      'flour, salt, corn flour, chicken, onion, soya sauce, chili sauce, fiske sauce, oister sauce',
    imageUrl: 'assets/images/toys/plane.jpeg',
    isLike: true,
    reaction: {
      numberLikes: 2,
      numberLoves: 0,
      numberDislikes: 0,
    },
    ratings: 9.5,
    active: false,
  },
  {
    toyOwner: 'avyaan',
    toyName: 'Dolfin',
    ageType: 'teen',
    toyCountry: 'Tha',
    toyCreated: new Date('16 / 03 / 2024'),
    toyPrice: 100,
    currency: 'DKK',
    detailsOfToy: 'dolfin of sea c',
    imageUrl: 'assets/images/toys/dolfin.jpeg',
    isLike: true,
    isLove: true,
    reaction: {
      numberLikes: 1,
      numberLoves: 2,
      numberDislikes: 0,
    },
    ratings: 8.5,
    active: true,
  },
  {
    toyOwner: 'ayan',
    toyName: 'Doll',
    ageType: 'bigboy',
    toyCountry: 'BGD',
    toyCreated: new Date('16 / 03 / 2024'),
    toyPrice: 90,
    currency: 'DKK',
    detailsOfToy: '',
    imageUrl: 'assets/images/toys/doll.jpeg',

    reaction: {
      numberLikes: 0,
      numberLoves: 0,
      numberDislikes: 0,
    },
    ratings: 8.5,
    active: true,
  },
  {
    toyOwner: 'farhad',
    toyName: 'Kite',
    ageType: 'kid',
    toyCountry: 'BGD',
    toyCreated: new Date('16 / 03 / 2024'),
    toyPrice: 100,
    currency: 'DKK',
    detailsOfToy: '',
    imageUrl: 'assets/images/toys/kite.jpeg',
    isDislike: true,
    reaction: {
      numberLikes: 0,
      numberLoves: 0,
      numberDislikes: 2,
    },
    ratings: 9.5,
    active: true,
  },
  {
    toyOwner: 'farhad',
    toyName: 'Dog',
    ageType: 'baby',
    toyCountry: 'CHN',
    toyCreated: new Date('16 / 03 / 2024'),
    toyPrice: 100,
    currency: 'DKK',
    detailsOfToy: '',
    imageUrl: 'assets/images/toys/dog.jpeg',
    isLike: true,
    isLove: true,
    reaction: {
      numberLikes: 5,
      numberLoves: 4,
      numberDislikes: 0,
    },
    ratings: 9.0,
    active: false,
  },
  {
    toyOwner: 'ayan',
    toyName: 'Joker',
    ageType: 'baby',
    toyCountry: 'CHN',
    toyCreated: new Date('16 / 03 / 2024'),
    toyPrice: 0,
    currency: 'DKK',
    detailsOfToy: '',
    imageUrl: 'assets/images/toys/joker.jpeg',
    isLike: true,
    isLove: true,
    reaction: {
      numberLikes: 5,
      numberLoves: 4,
      numberDislikes: 0,
    },
    ratings: 9.0,
    active: true,
  },
];
